yearsVersesArray: [ "Matthew 6:33", "John 1:1", "Genesis 1:1", "Galatians 2:20", "2 Timothy 3:16", "Psalms 1:1-2", "Proverbs 21:1", "Romans 1:19-20", "Ephesians 1:3-6", "Revelation 7:9-10", "James 4:7-8", "John 1:14" ]
